[2025-02-11T17:54:50.666+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-11T17:54:50.691+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_to_s3_pipeline.upload_to_s3 manual__2025-02-11T17:54:41.768780+00:00 [queued]>
[2025-02-11T17:54:50.705+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_to_s3_pipeline.upload_to_s3 manual__2025-02-11T17:54:41.768780+00:00 [queued]>
[2025-02-11T17:54:50.706+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-11T17:54:50.716+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): upload_to_s3> on 2025-02-11 17:54:41.768780+00:00
[2025-02-11T17:54:50.725+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=110) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-11T17:54:50.728+0000] {standard_task_runner.py:72} INFO - Started process 113 to run task
[2025-02-11T17:54:50.728+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kaggle_to_s3_pipeline', 'upload_to_s3', 'manual__2025-02-11T17:54:41.768780+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/s3_data.py', '--cfg-path', '/tmp/tmpsjtc_5it']
[2025-02-11T17:54:50.729+0000] {standard_task_runner.py:105} INFO - Job 19: Subtask upload_to_s3
[2025-02-11T17:54:50.777+0000] {task_command.py:467} INFO - Running <TaskInstance: kaggle_to_s3_pipeline.upload_to_s3 manual__2025-02-11T17:54:41.768780+00:00 [running]> on host c716bfbd0c9e
[2025-02-11T17:54:50.848+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_to_s3_pipeline' AIRFLOW_CTX_TASK_ID='upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T17:54:41.768780+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-11T17:54:41.768780+00:00'
[2025-02-11T17:54:50.849+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-11T17:54:50.863+0000] {s3_data.py:28} INFO - Uploading nba.sqlite to S3 bucket None at nba_data/nba.sqlite
[2025-02-11T17:54:54.028+0000] {s3_data.py:39} ERROR - Error uploading to S3: expected string or bytes-like object, got 'NoneType'
[2025-02-11T17:54:54.043+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-11T17:54:54.107+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-11T17:54:54.109+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=kaggle_to_s3_pipeline, task_id=upload_to_s3, run_id=manual__2025-02-11T17:54:41.768780+00:00, execution_date=20250211T175441, start_date=20250211T175450, end_date=20250211T175454
[2025-02-11T17:54:54.188+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-11T17:54:54.226+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-11T17:54:54.227+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
