[2025-02-11T16:36:42.377+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-11T16:36:42.391+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_to_s3_pipeline.upload_to_s3 manual__2025-02-11T16:36:36.884082+00:00 [queued]>
[2025-02-11T16:36:42.397+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_to_s3_pipeline.upload_to_s3 manual__2025-02-11T16:36:36.884082+00:00 [queued]>
[2025-02-11T16:36:42.397+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-11T16:36:42.404+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): upload_to_s3> on 2025-02-11 16:36:36.884082+00:00
[2025-02-11T16:36:42.412+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=124) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-11T16:36:42.415+0000] {standard_task_runner.py:72} INFO - Started process 125 to run task
[2025-02-11T16:36:42.417+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kaggle_to_s3_pipeline', 'upload_to_s3', 'manual__2025-02-11T16:36:36.884082+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/s3_data.py', '--cfg-path', '/tmp/tmp4jmr_as6']
[2025-02-11T16:36:42.419+0000] {standard_task_runner.py:105} INFO - Job 10: Subtask upload_to_s3
[2025-02-11T16:36:42.455+0000] {task_command.py:467} INFO - Running <TaskInstance: kaggle_to_s3_pipeline.upload_to_s3 manual__2025-02-11T16:36:36.884082+00:00 [running]> on host 84938a49bdc5
[2025-02-11T16:36:42.504+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_to_s3_pipeline' AIRFLOW_CTX_TASK_ID='upload_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T16:36:36.884082+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-11T16:36:36.884082+00:00'
[2025-02-11T16:36:42.505+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-11T16:36:42.517+0000] {s3_data.py:28} INFO - Uploading nba.sqlite to S3 bucket None at nba_data/nba.sqlite
[2025-02-11T16:36:45.053+0000] {s3_data.py:39} ERROR - Error uploading to S3: expected string or bytes-like object, got 'NoneType'
[2025-02-11T16:36:45.064+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-11T16:36:45.095+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-11T16:36:45.095+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=kaggle_to_s3_pipeline, task_id=upload_to_s3, run_id=manual__2025-02-11T16:36:36.884082+00:00, execution_date=20250211T163636, start_date=20250211T163642, end_date=20250211T163645
[2025-02-11T16:36:45.167+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-11T16:36:45.208+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-11T16:36:45.209+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
