[2025-02-11T18:01:30.265+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-11T18:01:30.304+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: read_sqlite.read_sqlite_data manual__2025-02-11T18:01:27.604757+00:00 [queued]>
[2025-02-11T18:01:30.315+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: read_sqlite.read_sqlite_data manual__2025-02-11T18:01:27.604757+00:00 [queued]>
[2025-02-11T18:01:30.316+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-11T18:01:30.339+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): read_sqlite_data> on 2025-02-11 18:01:27.604757+00:00
[2025-02-11T18:01:30.372+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=105) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-11T18:01:30.379+0000] {standard_task_runner.py:72} INFO - Started process 106 to run task
[2025-02-11T18:01:30.385+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'read_sqlite', 'read_sqlite_data', 'manual__2025-02-11T18:01:27.604757+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/read_sqlite.py', '--cfg-path', '/tmp/tmp12gizf2v']
[2025-02-11T18:01:30.399+0000] {standard_task_runner.py:105} INFO - Job 23: Subtask read_sqlite_data
[2025-02-11T18:01:30.487+0000] {task_command.py:467} INFO - Running <TaskInstance: read_sqlite.read_sqlite_data manual__2025-02-11T18:01:27.604757+00:00 [running]> on host 3aae20995624
[2025-02-11T18:01:30.702+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='read_sqlite' AIRFLOW_CTX_TASK_ID='read_sqlite_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T18:01:27.604757+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-11T18:01:27.604757+00:00'
[2025-02-11T18:01:30.705+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-11T18:01:30.762+0000] {read_sqlite.py:14} INFO - Connecting to SQLite database at /opt/***/data/nba.sqlite
[2025-02-11T18:01:30.781+0000] {read_sqlite.py:20} INFO - Tables found in SQLite database: []
[2025-02-11T18:01:30.783+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-11T18:01:30.808+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-11T18:01:30.808+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=read_sqlite, task_id=read_sqlite_data, run_id=manual__2025-02-11T18:01:27.604757+00:00, execution_date=20250211T180127, start_date=20250211T180130, end_date=20250211T180130
[2025-02-11T18:01:30.913+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-11T18:01:31.668+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-11T18:01:31.737+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
