[2025-02-12T00:33:24.728+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-12T00:33:24.742+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kaggle_to_s3_pipeline.download_kaggle_data scheduled__2025-02-11T00:00:00+00:00 [queued]>
[2025-02-12T00:33:24.747+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kaggle_to_s3_pipeline.download_kaggle_data scheduled__2025-02-11T00:00:00+00:00 [queued]>
[2025-02-12T00:33:24.748+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-02-12T00:33:24.756+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): download_kaggle_data> on 2025-02-11 00:00:00+00:00
[2025-02-12T00:33:24.774+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=84) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-12T00:33:24.778+0000] {standard_task_runner.py:72} INFO - Started process 85 to run task
[2025-02-12T00:33:24.778+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kaggle_to_s3_pipeline', 'download_kaggle_data', 'scheduled__2025-02-11T00:00:00+00:00', '--job-id', '81', '--raw', '--subdir', 'DAGS_FOLDER/s3_data.py', '--cfg-path', '/tmp/tmpn29sww76']
[2025-02-12T00:33:24.782+0000] {standard_task_runner.py:105} INFO - Job 81: Subtask download_kaggle_data
[2025-02-12T00:33:24.872+0000] {task_command.py:467} INFO - Running <TaskInstance: kaggle_to_s3_pipeline.download_kaggle_data scheduled__2025-02-11T00:00:00+00:00 [running]> on host 51b0f195f11f
[2025-02-12T00:33:24.960+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kaggle_to_s3_pipeline' AIRFLOW_CTX_TASK_ID='download_kaggle_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-11T00:00:00+00:00'
[2025-02-12T00:33:24.962+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-12T00:33:25.000+0000] {s3_data.py:30} INFO - Downloading dataset wyattowalsh/basketball to /opt/***/data
[2025-02-12T00:33:25.006+0000] {s3_data.py:38} ERROR - Download failed! /opt/***/data/nba.sqlite not found.
[2025-02-12T00:33:25.007+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-12T00:33:25.027+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-12T00:33:25.028+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=kaggle_to_s3_pipeline, task_id=download_kaggle_data, run_id=scheduled__2025-02-11T00:00:00+00:00, execution_date=20250211T000000, start_date=20250212T003324, end_date=20250212T003325
[2025-02-12T00:33:25.092+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-12T00:33:25.126+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-12T00:33:25.128+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
